window.INDIA_HOTELS = [
  {
    "id": "taj-lake-palace",
    "name": "Taj Lake Palace",
    "type": "hotels",
    "city": "Udaipur",
    "state": "Rajasthan",
    "rating": 4.9,
    "price": "₹7674/night",
    "image": "assets/images/hotels/taj-lake-palace.jpg",
    "description": "Premium accommodation in Udaipur."
  },
  {
    "id": "taj-mahal-palace-mumbai",
    "name": "Taj Mahal Palace Mumbai",
    "type": "hotels",
    "city": "Mumbai",
    "state": "Maharashtra",
    "rating": 4.5,
    "price": "₹7185/night",
    "image": "assets/images/hotels/taj-mahal-palace-mumbai.jpg",
    "description": "Premium accommodation in Mumbai."
  },
  {
    "id": "oberoi-amarvilas",
    "name": "Oberoi Amarvilas",
    "type": "hotels",
    "city": "Agra",
    "state": "Uttar Pradesh",
    "rating": 4.9,
    "price": "₹4654/night",
    "image": "assets/images/hotels/oberoi-amarvilas.jpg",
    "description": "Premium accommodation in Agra."
  },
  {
    "id": "oberoi-udaivilas",
    "name": "Oberoi Udaivilas",
    "type": "hotels",
    "city": "Udaipur",
    "state": "Rajasthan",
    "rating": 3.8,
    "price": "₹6568/night",
    "image": "assets/images/hotels/oberoi-udaivilas.jpg",
    "description": "Premium accommodation in Udaipur."
  },
  {
    "id": "itc-maurya-delhi",
    "name": "ITC Maurya Delhi",
    "type": "hotels",
    "city": "New Delhi",
    "state": "Delhi",
    "rating": 5,
    "price": "₹7453/night",
    "image": "assets/images/hotels/itc-maurya-delhi.jpg",
    "description": "Premium accommodation in New Delhi."
  },
  {
    "id": "itc-grand-chola",
    "name": "ITC Grand Chola",
    "type": "hotels",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "rating": 4.2,
    "price": "₹3412/night",
    "image": "assets/images/hotels/itc-grand-chola.jpg",
    "description": "Premium accommodation in Chennai."
  },
  {
    "id": "leela-palace-chennai",
    "name": "Leela Palace Chennai",
    "type": "hotels",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "rating": 4.6,
    "price": "₹7540/night",
    "image": "assets/images/hotels/leela-palace-chennai.jpg",
    "description": "Premium accommodation in Chennai."
  },
  {
    "id": "leela-palace-udaipur",
    "name": "Leela Palace Udaipur",
    "type": "hotels",
    "city": "Udaipur",
    "state": "Rajasthan",
    "rating": 4.5,
    "price": "₹4481/night",
    "image": "assets/images/hotels/leela-palace-udaipur.jpg",
    "description": "Premium accommodation in Udaipur."
  },
  {
    "id": "rambagh-palace",
    "name": "Rambagh Palace",
    "type": "hotels",
    "city": "Jaipur",
    "state": "Rajasthan",
    "rating": 4.5,
    "price": "₹6110/night",
    "image": "assets/images/hotels/rambagh-palace.jpg",
    "description": "Premium accommodation in Jaipur."
  },
  {
    "id": "wildflower-hall",
    "name": "Wildflower Hall",
    "type": "hotels",
    "city": "Shimla",
    "state": "Himachal Pradesh",
    "rating": 3.7,
    "price": "₹4331/night",
    "image": "assets/images/hotels/wildflower-hall.jpg",
    "description": "Premium accommodation in Shimla."
  },
  {
    "id": "goa-beach-resort",
    "name": "Goa Beach Resort",
    "type": "hotels",
    "city": "Goa",
    "state": "Goa",
    "rating": 3.6,
    "price": "₹3571/night",
    "image": "assets/images/hotels/goa-beach-resort.jpg",
    "description": "Premium accommodation in Goa."
  },
  {
    "id": "kerala-backwater-resort",
    "name": "Kerala Backwater Resort",
    "type": "hotels",
    "city": "Alappuzha",
    "state": "Kerala",
    "rating": 3.6,
    "price": "₹3553/night",
    "image": "assets/images/hotels/kerala-backwater-resort.jpg",
    "description": "Premium accommodation in Alappuzha."
  },
  {
    "id": "kovalam-resort",
    "name": "Kovalam Resort",
    "type": "hotels",
    "city": "Kovalam",
    "state": "Kerala",
    "rating": 4.4,
    "price": "₹3817/night",
    "image": "assets/images/hotels/kovalam-resort.jpg",
    "description": "Premium accommodation in Kovalam."
  },
  {
    "id": "andaman-island-resort",
    "name": "Andaman Island Resort",
    "type": "hotels",
    "city": "Port Blair",
    "state": "Andaman and Nicobar Islands",
    "rating": 3.6,
    "price": "₹7185/night",
    "image": "assets/images/hotels/andaman-island-resort.jpg",
    "description": "Premium accommodation in Port Blair."
  },
  {
    "id": "chennai-heritage-hotel",
    "name": "Chennai Heritage Hotel",
    "type": "hotels",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "rating": 5,
    "price": "₹6250/night",
    "image": "assets/images/hotels/chennai-heritage-hotel.jpg",
    "description": "Premium accommodation in Chennai."
  },
  {
    "id": "mumbai-central-hotel",
    "name": "Mumbai Central Hotel",
    "type": "hotels",
    "city": "Mumbai",
    "state": "Maharashtra",
    "rating": 3.7,
    "price": "₹5189/night",
    "image": "assets/images/hotels/mumbai-central-hotel.jpg",
    "description": "Premium accommodation in Mumbai."
  },
  {
    "id": "delhi-grand-hotel",
    "name": "Delhi Grand Hotel",
    "type": "hotels",
    "city": "New Delhi",
    "state": "Delhi",
    "rating": 4.6,
    "price": "₹5989/night",
    "image": "assets/images/hotels/delhi-grand-hotel.jpg",
    "description": "Premium accommodation in New Delhi."
  },
  {
    "id": "bangalore-palace-hotel",
    "name": "Bangalore Palace Hotel",
    "type": "hotels",
    "city": "Bengaluru",
    "state": "Karnataka",
    "rating": 4,
    "price": "₹3377/night",
    "image": "assets/images/hotels/bangalore-palace-hotel.jpg",
    "description": "Premium accommodation in Bengaluru."
  },
  {
    "id": "hyderabad-royal-hotel",
    "name": "Hyderabad Royal Hotel",
    "type": "hotels",
    "city": "Hyderabad",
    "state": "Telangana",
    "rating": 4.7,
    "price": "₹6334/night",
    "image": "assets/images/hotels/hyderabad-royal-hotel.jpg",
    "description": "Premium accommodation in Hyderabad."
  },
  {
    "id": "jaipur-heritage-hotel",
    "name": "Jaipur Heritage Hotel",
    "type": "hotels",
    "city": "Jaipur",
    "state": "Rajasthan",
    "rating": 5,
    "price": "₹7568/night",
    "image": "assets/images/hotels/jaipur-heritage-hotel.jpg",
    "description": "Premium accommodation in Jaipur."
  },
  {
    "id": "kolkata-grand-hotel",
    "name": "Kolkata Grand Hotel",
    "type": "hotels",
    "city": "Kolkata",
    "state": "West Bengal",
    "rating": 3.6,
    "price": "₹6897/night",
    "image": "assets/images/hotels/kolkata-grand-hotel.jpg",
    "description": "Premium accommodation in Kolkata."
  },
  {
    "id": "amaravati-hotel-21",
    "name": "Amaravati Resort",
    "type": "hotels",
    "city": "Amaravati",
    "state": "Andhra Pradesh",
    "rating": 3.6,
    "price": "₹8866/night",
    "image": "assets/images/hotels/amaravati-hotel-21.jpg",
    "description": "A comfortable stay at Amaravati."
  },
  {
    "id": "amaravati-hotel-22",
    "name": "Amaravati Budget Hotel",
    "type": "hotels",
    "city": "Amaravati",
    "state": "Andhra Pradesh",
    "rating": 4.6,
    "price": "₹2914/night",
    "image": "assets/images/hotels/amaravati-hotel-22.jpg",
    "description": "A comfortable stay at Amaravati."
  },
  {
    "id": "vijayawada-hotel-23",
    "name": "Vijayawada Budget Hotel",
    "type": "hotels",
    "city": "Vijayawada",
    "state": "Andhra Pradesh",
    "rating": 4.4,
    "price": "₹3616/night",
    "image": "assets/images/hotels/vijayawada-hotel-23.jpg",
    "description": "A comfortable stay at Vijayawada."
  },
  {
    "id": "visakhapatnam-hotel-24",
    "name": "Visakhapatnam Heritage Hotel",
    "type": "hotels",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "rating": 4.4,
    "price": "₹2996/night",
    "image": "assets/images/hotels/visakhapatnam-hotel-24.jpg",
    "description": "A comfortable stay at Visakhapatnam."
  },
  {
    "id": "tirupati-hotel-25",
    "name": "Tirupati Heritage Hotel",
    "type": "hotels",
    "city": "Tirupati",
    "state": "Andhra Pradesh",
    "rating": 4.4,
    "price": "₹5878/night",
    "image": "assets/images/hotels/tirupati-hotel-25.jpg",
    "description": "A comfortable stay at Tirupati."
  },
  {
    "id": "visakhapatnam-hotel-26",
    "name": "Visakhapatnam Heritage Hotel",
    "type": "hotels",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "rating": 3.5,
    "price": "₹8677/night",
    "image": "assets/images/hotels/visakhapatnam-hotel-26.jpg",
    "description": "A comfortable stay at Visakhapatnam."
  },
  {
    "id": "tawang-hotel-27",
    "name": "Tawang Budget Hotel",
    "type": "hotels",
    "city": "Tawang",
    "state": "Arunachal Pradesh",
    "rating": 4.7,
    "price": "₹3537/night",
    "image": "assets/images/hotels/tawang-hotel-27.jpg",
    "description": "A comfortable stay at Tawang."
  },
  {
    "id": "tawang-hotel-28",
    "name": "Tawang Heritage Hotel",
    "type": "hotels",
    "city": "Tawang",
    "state": "Arunachal Pradesh",
    "rating": 4,
    "price": "₹3671/night",
    "image": "assets/images/hotels/tawang-hotel-28.jpg",
    "description": "A comfortable stay at Tawang."
  },
  {
    "id": "ziro-hotel-29",
    "name": "Ziro Budget Hotel",
    "type": "hotels",
    "city": "Ziro",
    "state": "Arunachal Pradesh",
    "rating": 4.7,
    "price": "₹1663/night",
    "image": "assets/images/hotels/ziro-hotel-29.jpg",
    "description": "A comfortable stay at Ziro."
  },
  {
    "id": "tawang-hotel-30",
    "name": "Tawang Resort",
    "type": "hotels",
    "city": "Tawang",
    "state": "Arunachal Pradesh",
    "rating": 4.9,
    "price": "₹6289/night",
    "image": "assets/images/hotels/tawang-hotel-30.jpg",
    "description": "A comfortable stay at Tawang."
  },
  {
    "id": "itanagar-hotel-31",
    "name": "Itanagar Budget Hotel",
    "type": "hotels",
    "city": "Itanagar",
    "state": "Arunachal Pradesh",
    "rating": 4.6,
    "price": "₹8271/night",
    "image": "assets/images/hotels/itanagar-hotel-31.jpg",
    "description": "A comfortable stay at Itanagar."
  },
  {
    "id": "itanagar-hotel-32",
    "name": "Itanagar Luxury Hotel",
    "type": "hotels",
    "city": "Itanagar",
    "state": "Arunachal Pradesh",
    "rating": 4.6,
    "price": "₹4288/night",
    "image": "assets/images/hotels/itanagar-hotel-32.jpg",
    "description": "A comfortable stay at Itanagar."
  },
  {
    "id": "guwahati-hotel-33",
    "name": "Guwahati Budget Hotel",
    "type": "hotels",
    "city": "Guwahati",
    "state": "Assam",
    "rating": 4.9,
    "price": "₹1202/night",
    "image": "assets/images/hotels/guwahati-hotel-33.jpg",
    "description": "A comfortable stay at Guwahati."
  },
  {
    "id": "majuli-hotel-34",
    "name": "Majuli Luxury Hotel",
    "type": "hotels",
    "city": "Majuli",
    "state": "Assam",
    "rating": 4,
    "price": "₹4567/night",
    "image": "assets/images/hotels/majuli-hotel-34.jpg",
    "description": "A comfortable stay at Majuli."
  },
  {
    "id": "guwahati-hotel-35",
    "name": "Guwahati Grand",
    "type": "hotels",
    "city": "Guwahati",
    "state": "Assam",
    "rating": 3.9,
    "price": "₹2343/night",
    "image": "assets/images/hotels/guwahati-hotel-35.jpg",
    "description": "A comfortable stay at Guwahati."
  },
  {
    "id": "guwahati-hotel-36",
    "name": "Guwahati Resort",
    "type": "hotels",
    "city": "Guwahati",
    "state": "Assam",
    "rating": 4,
    "price": "₹6740/night",
    "image": "assets/images/hotels/guwahati-hotel-36.jpg",
    "description": "A comfortable stay at Guwahati."
  },
  {
    "id": "kaziranga-hotel-37",
    "name": "Kaziranga Luxury Hotel",
    "type": "hotels",
    "city": "Kaziranga",
    "state": "Assam",
    "rating": 4.5,
    "price": "₹8986/night",
    "image": "assets/images/hotels/kaziranga-hotel-37.jpg",
    "description": "A comfortable stay at Kaziranga."
  },
  {
    "id": "majuli-hotel-38",
    "name": "Majuli Heritage Hotel",
    "type": "hotels",
    "city": "Majuli",
    "state": "Assam",
    "rating": 4.5,
    "price": "₹4102/night",
    "image": "assets/images/hotels/majuli-hotel-38.jpg",
    "description": "A comfortable stay at Majuli."
  },
  {
    "id": "bodh-gaya-hotel-39",
    "name": "Bodh Gaya Resort",
    "type": "hotels",
    "city": "Bodh Gaya",
    "state": "Bihar",
    "rating": 4.5,
    "price": "₹3463/night",
    "image": "assets/images/hotels/bodh-gaya-hotel-39.jpg",
    "description": "A comfortable stay at Bodh Gaya."
  },
  {
    "id": "bodh-gaya-hotel-40",
    "name": "Bodh Gaya Resort",
    "type": "hotels",
    "city": "Bodh Gaya",
    "state": "Bihar",
    "rating": 3.7,
    "price": "₹4881/night",
    "image": "assets/images/hotels/bodh-gaya-hotel-40.jpg",
    "description": "A comfortable stay at Bodh Gaya."
  },
  {
    "id": "bodh-gaya-hotel-41",
    "name": "Bodh Gaya Resort",
    "type": "hotels",
    "city": "Bodh Gaya",
    "state": "Bihar",
    "rating": 4.6,
    "price": "₹2421/night",
    "image": "assets/images/hotels/bodh-gaya-hotel-41.jpg",
    "description": "A comfortable stay at Bodh Gaya."
  },
  {
    "id": "bodh-gaya-hotel-42",
    "name": "Bodh Gaya Resort",
    "type": "hotels",
    "city": "Bodh Gaya",
    "state": "Bihar",
    "rating": 4.4,
    "price": "₹7298/night",
    "image": "assets/images/hotels/bodh-gaya-hotel-42.jpg",
    "description": "A comfortable stay at Bodh Gaya."
  },
  {
    "id": "rajgir-hotel-43",
    "name": "Rajgir Grand",
    "type": "hotels",
    "city": "Rajgir",
    "state": "Bihar",
    "rating": 4.3,
    "price": "₹3380/night",
    "image": "assets/images/hotels/rajgir-hotel-43.jpg",
    "description": "A comfortable stay at Rajgir."
  },
  {
    "id": "rajgir-hotel-44",
    "name": "Rajgir Resort",
    "type": "hotels",
    "city": "Rajgir",
    "state": "Bihar",
    "rating": 3.6,
    "price": "₹5338/night",
    "image": "assets/images/hotels/rajgir-hotel-44.jpg",
    "description": "A comfortable stay at Rajgir."
  },
  {
    "id": "jagdalpur-hotel-45",
    "name": "Jagdalpur Luxury Hotel",
    "type": "hotels",
    "city": "Jagdalpur",
    "state": "Chhattisgarh",
    "rating": 4.8,
    "price": "₹2954/night",
    "image": "assets/images/hotels/jagdalpur-hotel-45.jpg",
    "description": "A comfortable stay at Jagdalpur."
  },
  {
    "id": "jagdalpur-hotel-46",
    "name": "Jagdalpur Luxury Hotel",
    "type": "hotels",
    "city": "Jagdalpur",
    "state": "Chhattisgarh",
    "rating": 4.7,
    "price": "₹1724/night",
    "image": "assets/images/hotels/jagdalpur-hotel-46.jpg",
    "description": "A comfortable stay at Jagdalpur."
  },
  {
    "id": "jagdalpur-hotel-47",
    "name": "Jagdalpur Luxury Hotel",
    "type": "hotels",
    "city": "Jagdalpur",
    "state": "Chhattisgarh",
    "rating": 4.3,
    "price": "₹6387/night",
    "image": "assets/images/hotels/jagdalpur-hotel-47.jpg",
    "description": "A comfortable stay at Jagdalpur."
  },
  {
    "id": "jagdalpur-hotel-48",
    "name": "Jagdalpur Resort",
    "type": "hotels",
    "city": "Jagdalpur",
    "state": "Chhattisgarh",
    "rating": 3.7,
    "price": "₹6489/night",
    "image": "assets/images/hotels/jagdalpur-hotel-48.jpg",
    "description": "A comfortable stay at Jagdalpur."
  },
  {
    "id": "bhilai-hotel-49",
    "name": "Bhilai Heritage Hotel",
    "type": "hotels",
    "city": "Bhilai",
    "state": "Chhattisgarh",
    "rating": 3.7,
    "price": "₹2067/night",
    "image": "assets/images/hotels/bhilai-hotel-49.jpg",
    "description": "A comfortable stay at Bhilai."
  },
  {
    "id": "jagdalpur-hotel-50",
    "name": "Jagdalpur Budget Hotel",
    "type": "hotels",
    "city": "Jagdalpur",
    "state": "Chhattisgarh",
    "rating": 3.5,
    "price": "₹2386/night",
    "image": "assets/images/hotels/jagdalpur-hotel-50.jpg",
    "description": "A comfortable stay at Jagdalpur."
  },
  {
    "id": "panaji-hotel-51",
    "name": "Panaji Heritage Hotel",
    "type": "hotels",
    "city": "Panaji",
    "state": "Goa",
    "rating": 3.6,
    "price": "₹6224/night",
    "image": "assets/images/hotels/panaji-hotel-51.jpg",
    "description": "A comfortable stay at Panaji."
  },
  {
    "id": "baga-hotel-52",
    "name": "Baga Grand",
    "type": "hotels",
    "city": "Baga",
    "state": "Goa",
    "rating": 3.6,
    "price": "₹3371/night",
    "image": "assets/images/hotels/baga-hotel-52.jpg",
    "description": "A comfortable stay at Baga."
  },
  {
    "id": "anjuna-hotel-53",
    "name": "Anjuna Grand",
    "type": "hotels",
    "city": "Anjuna",
    "state": "Goa",
    "rating": 3.7,
    "price": "₹5253/night",
    "image": "assets/images/hotels/anjuna-hotel-53.jpg",
    "description": "A comfortable stay at Anjuna."
  },
  {
    "id": "baga-hotel-54",
    "name": "Baga Grand",
    "type": "hotels",
    "city": "Baga",
    "state": "Goa",
    "rating": 4.9,
    "price": "₹5307/night",
    "image": "assets/images/hotels/baga-hotel-54.jpg",
    "description": "A comfortable stay at Baga."
  },
  {
    "id": "anjuna-hotel-55",
    "name": "Anjuna Luxury Hotel",
    "type": "hotels",
    "city": "Anjuna",
    "state": "Goa",
    "rating": 4.9,
    "price": "₹1721/night",
    "image": "assets/images/hotels/anjuna-hotel-55.jpg",
    "description": "A comfortable stay at Anjuna."
  },
  {
    "id": "panaji-hotel-56",
    "name": "Panaji Heritage Hotel",
    "type": "hotels",
    "city": "Panaji",
    "state": "Goa",
    "rating": 4.9,
    "price": "₹8581/night",
    "image": "assets/images/hotels/panaji-hotel-56.jpg",
    "description": "A comfortable stay at Panaji."
  },
  {
    "id": "vadodara-hotel-57",
    "name": "Vadodara Heritage Hotel",
    "type": "hotels",
    "city": "Vadodara",
    "state": "Gujarat",
    "rating": 3.5,
    "price": "₹3902/night",
    "image": "assets/images/hotels/vadodara-hotel-57.jpg",
    "description": "A comfortable stay at Vadodara."
  },
  {
    "id": "somnath-hotel-58",
    "name": "Somnath Resort",
    "type": "hotels",
    "city": "Somnath",
    "state": "Gujarat",
    "rating": 3.8,
    "price": "₹1024/night",
    "image": "assets/images/hotels/somnath-hotel-58.jpg",
    "description": "A comfortable stay at Somnath."
  },
  {
    "id": "vadodara-hotel-59",
    "name": "Vadodara Luxury Hotel",
    "type": "hotels",
    "city": "Vadodara",
    "state": "Gujarat",
    "rating": 4,
    "price": "₹3416/night",
    "image": "assets/images/hotels/vadodara-hotel-59.jpg",
    "description": "A comfortable stay at Vadodara."
  },
  {
    "id": "ahmedabad-hotel-60",
    "name": "Ahmedabad Heritage Hotel",
    "type": "hotels",
    "city": "Ahmedabad",
    "state": "Gujarat",
    "rating": 3.6,
    "price": "₹2991/night",
    "image": "assets/images/hotels/ahmedabad-hotel-60.jpg",
    "description": "A comfortable stay at Ahmedabad."
  },
  {
    "id": "surat-hotel-61",
    "name": "Surat Resort",
    "type": "hotels",
    "city": "Surat",
    "state": "Gujarat",
    "rating": 4.8,
    "price": "₹3584/night",
    "image": "assets/images/hotels/surat-hotel-61.jpg",
    "description": "A comfortable stay at Surat."
  },
  {
    "id": "surat-hotel-62",
    "name": "Surat Grand",
    "type": "hotels",
    "city": "Surat",
    "state": "Gujarat",
    "rating": 4.4,
    "price": "₹8340/night",
    "image": "assets/images/hotels/surat-hotel-62.jpg",
    "description": "A comfortable stay at Surat."
  },
  {
    "id": "kurukshetra-hotel-63",
    "name": "Kurukshetra Grand",
    "type": "hotels",
    "city": "Kurukshetra",
    "state": "Haryana",
    "rating": 3.8,
    "price": "₹7772/night",
    "image": "assets/images/hotels/kurukshetra-hotel-63.jpg",
    "description": "A comfortable stay at Kurukshetra."
  },
  {
    "id": "kurukshetra-hotel-64",
    "name": "Kurukshetra Heritage Hotel",
    "type": "hotels",
    "city": "Kurukshetra",
    "state": "Haryana",
    "rating": 4.3,
    "price": "₹7524/night",
    "image": "assets/images/hotels/kurukshetra-hotel-64.jpg",
    "description": "A comfortable stay at Kurukshetra."
  },
  {
    "id": "kurukshetra-hotel-65",
    "name": "Kurukshetra Budget Hotel",
    "type": "hotels",
    "city": "Kurukshetra",
    "state": "Haryana",
    "rating": 4.4,
    "price": "₹3581/night",
    "image": "assets/images/hotels/kurukshetra-hotel-65.jpg",
    "description": "A comfortable stay at Kurukshetra."
  },
  {
    "id": "panipat-hotel-66",
    "name": "Panipat Heritage Hotel",
    "type": "hotels",
    "city": "Panipat",
    "state": "Haryana",
    "rating": 4.7,
    "price": "₹2917/night",
    "image": "assets/images/hotels/panipat-hotel-66.jpg",
    "description": "A comfortable stay at Panipat."
  },
  {
    "id": "panipat-hotel-67",
    "name": "Panipat Luxury Hotel",
    "type": "hotels",
    "city": "Panipat",
    "state": "Haryana",
    "rating": 3.8,
    "price": "₹1323/night",
    "image": "assets/images/hotels/panipat-hotel-67.jpg",
    "description": "A comfortable stay at Panipat."
  },
  {
    "id": "gurugram-hotel-68",
    "name": "Gurugram Resort",
    "type": "hotels",
    "city": "Gurugram",
    "state": "Haryana",
    "rating": 4.9,
    "price": "₹3174/night",
    "image": "assets/images/hotels/gurugram-hotel-68.jpg",
    "description": "A comfortable stay at Gurugram."
  },
  {
    "id": "kasol-hotel-69",
    "name": "Kasol Luxury Hotel",
    "type": "hotels",
    "city": "Kasol",
    "state": "Himachal Pradesh",
    "rating": 4.9,
    "price": "₹8156/night",
    "image": "assets/images/hotels/kasol-hotel-69.jpg",
    "description": "A comfortable stay at Kasol."
  },
  {
    "id": "manali-hotel-70",
    "name": "Manali Luxury Hotel",
    "type": "hotels",
    "city": "Manali",
    "state": "Himachal Pradesh",
    "rating": 4.3,
    "price": "₹8604/night",
    "image": "assets/images/hotels/manali-hotel-70.jpg",
    "description": "A comfortable stay at Manali."
  },
  {
    "id": "dharamshala-hotel-71",
    "name": "Dharamshala Budget Hotel",
    "type": "hotels",
    "city": "Dharamshala",
    "state": "Himachal Pradesh",
    "rating": 4.1,
    "price": "₹3412/night",
    "image": "assets/images/hotels/dharamshala-hotel-71.jpg",
    "description": "A comfortable stay at Dharamshala."
  },
  {
    "id": "dharamshala-hotel-72",
    "name": "Dharamshala Budget Hotel",
    "type": "hotels",
    "city": "Dharamshala",
    "state": "Himachal Pradesh",
    "rating": 4,
    "price": "₹6463/night",
    "image": "assets/images/hotels/dharamshala-hotel-72.jpg",
    "description": "A comfortable stay at Dharamshala."
  },
  {
    "id": "manali-hotel-73",
    "name": "Manali Grand",
    "type": "hotels",
    "city": "Manali",
    "state": "Himachal Pradesh",
    "rating": 4.1,
    "price": "₹2210/night",
    "image": "assets/images/hotels/manali-hotel-73.jpg",
    "description": "A comfortable stay at Manali."
  },
  {
    "id": "manali-hotel-74",
    "name": "Manali Heritage Hotel",
    "type": "hotels",
    "city": "Manali",
    "state": "Himachal Pradesh",
    "rating": 3.5,
    "price": "₹8620/night",
    "image": "assets/images/hotels/manali-hotel-74.jpg",
    "description": "A comfortable stay at Manali."
  },
  {
    "id": "jamshedpur-hotel-75",
    "name": "Jamshedpur Budget Hotel",
    "type": "hotels",
    "city": "Jamshedpur",
    "state": "Jharkhand",
    "rating": 3.9,
    "price": "₹7442/night",
    "image": "assets/images/hotels/jamshedpur-hotel-75.jpg",
    "description": "A comfortable stay at Jamshedpur."
  },
  {
    "id": "ranchi-hotel-76",
    "name": "Ranchi Luxury Hotel",
    "type": "hotels",
    "city": "Ranchi",
    "state": "Jharkhand",
    "rating": 3.7,
    "price": "₹1567/night",
    "image": "assets/images/hotels/ranchi-hotel-76.jpg",
    "description": "A comfortable stay at Ranchi."
  },
  {
    "id": "jamshedpur-hotel-77",
    "name": "Jamshedpur Budget Hotel",
    "type": "hotels",
    "city": "Jamshedpur",
    "state": "Jharkhand",
    "rating": 4.3,
    "price": "₹7569/night",
    "image": "assets/images/hotels/jamshedpur-hotel-77.jpg",
    "description": "A comfortable stay at Jamshedpur."
  },
  {
    "id": "jamshedpur-hotel-78",
    "name": "Jamshedpur Luxury Hotel",
    "type": "hotels",
    "city": "Jamshedpur",
    "state": "Jharkhand",
    "rating": 3.9,
    "price": "₹2144/night",
    "image": "assets/images/hotels/jamshedpur-hotel-78.jpg",
    "description": "A comfortable stay at Jamshedpur."
  },
  {
    "id": "jamshedpur-hotel-79",
    "name": "Jamshedpur Luxury Hotel",
    "type": "hotels",
    "city": "Jamshedpur",
    "state": "Jharkhand",
    "rating": 4.7,
    "price": "₹7121/night",
    "image": "assets/images/hotels/jamshedpur-hotel-79.jpg",
    "description": "A comfortable stay at Jamshedpur."
  },
  {
    "id": "deoghar-hotel-80",
    "name": "Deoghar Budget Hotel",
    "type": "hotels",
    "city": "Deoghar",
    "state": "Jharkhand",
    "rating": 4.9,
    "price": "₹5498/night",
    "image": "assets/images/hotels/deoghar-hotel-80.jpg",
    "description": "A comfortable stay at Deoghar."
  },
  {
    "id": "bengaluru-hotel-81",
    "name": "Bengaluru Budget Hotel",
    "type": "hotels",
    "city": "Bengaluru",
    "state": "Karnataka",
    "rating": 4.4,
    "price": "₹3929/night",
    "image": "assets/images/hotels/bengaluru-hotel-81.jpg",
    "description": "A comfortable stay at Bengaluru."
  },
  {
    "id": "coorg-hotel-82",
    "name": "Coorg Heritage Hotel",
    "type": "hotels",
    "city": "Coorg",
    "state": "Karnataka",
    "rating": 3.9,
    "price": "₹7908/night",
    "image": "assets/images/hotels/coorg-hotel-82.jpg",
    "description": "A comfortable stay at Coorg."
  },
  {
    "id": "gokarna-hotel-83",
    "name": "Gokarna Luxury Hotel",
    "type": "hotels",
    "city": "Gokarna",
    "state": "Karnataka",
    "rating": 4,
    "price": "₹7274/night",
    "image": "assets/images/hotels/gokarna-hotel-83.jpg",
    "description": "A comfortable stay at Gokarna."
  },
  {
    "id": "coorg-hotel-84",
    "name": "Coorg Budget Hotel",
    "type": "hotels",
    "city": "Coorg",
    "state": "Karnataka",
    "rating": 3.6,
    "price": "₹6794/night",
    "image": "assets/images/hotels/coorg-hotel-84.jpg",
    "description": "A comfortable stay at Coorg."
  },
  {
    "id": "mangaluru-hotel-85",
    "name": "Mangaluru Resort",
    "type": "hotels",
    "city": "Mangaluru",
    "state": "Karnataka",
    "rating": 4.6,
    "price": "₹4164/night",
    "image": "assets/images/hotels/mangaluru-hotel-85.jpg",
    "description": "A comfortable stay at Mangaluru."
  },
  {
    "id": "mangaluru-hotel-86",
    "name": "Mangaluru Heritage Hotel",
    "type": "hotels",
    "city": "Mangaluru",
    "state": "Karnataka",
    "rating": 3.6,
    "price": "₹6108/night",
    "image": "assets/images/hotels/mangaluru-hotel-86.jpg",
    "description": "A comfortable stay at Mangaluru."
  },
  {
    "id": "wayanad-hotel-87",
    "name": "Wayanad Resort",
    "type": "hotels",
    "city": "Wayanad",
    "state": "Kerala",
    "rating": 3.6,
    "price": "₹3756/night",
    "image": "assets/images/hotels/wayanad-hotel-87.jpg",
    "description": "A comfortable stay at Wayanad."
  },
  {
    "id": "munnar-hotel-88",
    "name": "Munnar Resort",
    "type": "hotels",
    "city": "Munnar",
    "state": "Kerala",
    "rating": 4.2,
    "price": "₹5382/night",
    "image": "assets/images/hotels/munnar-hotel-88.jpg",
    "description": "A comfortable stay at Munnar."
  },
  {
    "id": "wayanad-hotel-89",
    "name": "Wayanad Resort",
    "type": "hotels",
    "city": "Wayanad",
    "state": "Kerala",
    "rating": 3.9,
    "price": "₹7723/night",
    "image": "assets/images/hotels/wayanad-hotel-89.jpg",
    "description": "A comfortable stay at Wayanad."
  },
  {
    "id": "kovalam-hotel-90",
    "name": "Kovalam Budget Hotel",
    "type": "hotels",
    "city": "Kovalam",
    "state": "Kerala",
    "rating": 4.3,
    "price": "₹1873/night",
    "image": "assets/images/hotels/kovalam-hotel-90.jpg",
    "description": "A comfortable stay at Kovalam."
  },
  {
    "id": "kovalam-hotel-91",
    "name": "Kovalam Luxury Hotel",
    "type": "hotels",
    "city": "Kovalam",
    "state": "Kerala",
    "rating": 3.9,
    "price": "₹1188/night",
    "image": "assets/images/hotels/kovalam-hotel-91.jpg",
    "description": "A comfortable stay at Kovalam."
  },
  {
    "id": "kovalam-hotel-92",
    "name": "Kovalam Heritage Hotel",
    "type": "hotels",
    "city": "Kovalam",
    "state": "Kerala",
    "rating": 3.5,
    "price": "₹2785/night",
    "image": "assets/images/hotels/kovalam-hotel-92.jpg",
    "description": "A comfortable stay at Kovalam."
  },
  {
    "id": "bhopal-hotel-93",
    "name": "Bhopal Grand",
    "type": "hotels",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "rating": 4.8,
    "price": "₹2135/night",
    "image": "assets/images/hotels/bhopal-hotel-93.jpg",
    "description": "A comfortable stay at Bhopal."
  },
  {
    "id": "bhopal-hotel-94",
    "name": "Bhopal Resort",
    "type": "hotels",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "rating": 4.4,
    "price": "₹5157/night",
    "image": "assets/images/hotels/bhopal-hotel-94.jpg",
    "description": "A comfortable stay at Bhopal."
  },
  {
    "id": "bhopal-hotel-95",
    "name": "Bhopal Budget Hotel",
    "type": "hotels",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "rating": 4.6,
    "price": "₹3517/night",
    "image": "assets/images/hotels/bhopal-hotel-95.jpg",
    "description": "A comfortable stay at Bhopal."
  },
  {
    "id": "khajuraho-hotel-96",
    "name": "Khajuraho Resort",
    "type": "hotels",
    "city": "Khajuraho",
    "state": "Madhya Pradesh",
    "rating": 3.9,
    "price": "₹7891/night",
    "image": "assets/images/hotels/khajuraho-hotel-96.jpg",
    "description": "A comfortable stay at Khajuraho."
  },
  {
    "id": "ujjain-hotel-97",
    "name": "Ujjain Resort",
    "type": "hotels",
    "city": "Ujjain",
    "state": "Madhya Pradesh",
    "rating": 4.9,
    "price": "₹2035/night",
    "image": "assets/images/hotels/ujjain-hotel-97.jpg",
    "description": "A comfortable stay at Ujjain."
  },
  {
    "id": "gwalior-hotel-98",
    "name": "Gwalior Budget Hotel",
    "type": "hotels",
    "city": "Gwalior",
    "state": "Madhya Pradesh",
    "rating": 4.6,
    "price": "₹6136/night",
    "image": "assets/images/hotels/gwalior-hotel-98.jpg",
    "description": "A comfortable stay at Gwalior."
  },
  {
    "id": "mahabaleshwar-hotel-99",
    "name": "Mahabaleshwar Grand",
    "type": "hotels",
    "city": "Mahabaleshwar",
    "state": "Maharashtra",
    "rating": 4,
    "price": "₹3248/night",
    "image": "assets/images/hotels/mahabaleshwar-hotel-99.jpg",
    "description": "A comfortable stay at Mahabaleshwar."
  },
  {
    "id": "pune-hotel-100",
    "name": "Pune Grand",
    "type": "hotels",
    "city": "Pune",
    "state": "Maharashtra",
    "rating": 4.9,
    "price": "₹4021/night",
    "image": "assets/images/hotels/pune-hotel-100.jpg",
    "description": "A comfortable stay at Pune."
  },
  {
    "id": "nagpur-hotel-101",
    "name": "Nagpur Resort",
    "type": "hotels",
    "city": "Nagpur",
    "state": "Maharashtra",
    "rating": 3.8,
    "price": "₹6079/night",
    "image": "assets/images/hotels/nagpur-hotel-101.jpg",
    "description": "A comfortable stay at Nagpur."
  },
  {
    "id": "mahabaleshwar-hotel-102",
    "name": "Mahabaleshwar Grand",
    "type": "hotels",
    "city": "Mahabaleshwar",
    "state": "Maharashtra",
    "rating": 4.6,
    "price": "₹7737/night",
    "image": "assets/images/hotels/mahabaleshwar-hotel-102.jpg",
    "description": "A comfortable stay at Mahabaleshwar."
  },
  {
    "id": "nagpur-hotel-103",
    "name": "Nagpur Heritage Hotel",
    "type": "hotels",
    "city": "Nagpur",
    "state": "Maharashtra",
    "rating": 3.9,
    "price": "₹2218/night",
    "image": "assets/images/hotels/nagpur-hotel-103.jpg",
    "description": "A comfortable stay at Nagpur."
  },
  {
    "id": "mahabaleshwar-hotel-104",
    "name": "Mahabaleshwar Luxury Hotel",
    "type": "hotels",
    "city": "Mahabaleshwar",
    "state": "Maharashtra",
    "rating": 4.3,
    "price": "₹1861/night",
    "image": "assets/images/hotels/mahabaleshwar-hotel-104.jpg",
    "description": "A comfortable stay at Mahabaleshwar."
  },
  {
    "id": "loktak-hotel-105",
    "name": "Loktak Budget Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 5,
    "price": "₹6278/night",
    "image": "assets/images/hotels/loktak-hotel-105.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "loktak-hotel-106",
    "name": "Loktak Budget Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 3.9,
    "price": "₹3508/night",
    "image": "assets/images/hotels/loktak-hotel-106.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "loktak-hotel-107",
    "name": "Loktak Heritage Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 3.7,
    "price": "₹2875/night",
    "image": "assets/images/hotels/loktak-hotel-107.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "loktak-hotel-108",
    "name": "Loktak Budget Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 3.6,
    "price": "₹6434/night",
    "image": "assets/images/hotels/loktak-hotel-108.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "loktak-hotel-109",
    "name": "Loktak Heritage Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 3.9,
    "price": "₹2139/night",
    "image": "assets/images/hotels/loktak-hotel-109.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "loktak-hotel-110",
    "name": "Loktak Heritage Hotel",
    "type": "hotels",
    "city": "Loktak",
    "state": "Manipur",
    "rating": 4.5,
    "price": "₹7249/night",
    "image": "assets/images/hotels/loktak-hotel-110.jpg",
    "description": "A comfortable stay at Loktak."
  },
  {
    "id": "shillong-hotel-111",
    "name": "Shillong Heritage Hotel",
    "type": "hotels",
    "city": "Shillong",
    "state": "Meghalaya",
    "rating": 4.1,
    "price": "₹7231/night",
    "image": "assets/images/hotels/shillong-hotel-111.jpg",
    "description": "A comfortable stay at Shillong."
  },
  {
    "id": "dawki-hotel-112",
    "name": "Dawki Luxury Hotel",
    "type": "hotels",
    "city": "Dawki",
    "state": "Meghalaya",
    "rating": 4.1,
    "price": "₹4260/night",
    "image": "assets/images/hotels/dawki-hotel-112.jpg",
    "description": "A comfortable stay at Dawki."
  },
  {
    "id": "dawki-hotel-113",
    "name": "Dawki Grand",
    "type": "hotels",
    "city": "Dawki",
    "state": "Meghalaya",
    "rating": 3.7,
    "price": "₹1124/night",
    "image": "assets/images/hotels/dawki-hotel-113.jpg",
    "description": "A comfortable stay at Dawki."
  },
  {
    "id": "dawki-hotel-114",
    "name": "Dawki Luxury Hotel",
    "type": "hotels",
    "city": "Dawki",
    "state": "Meghalaya",
    "rating": 4.6,
    "price": "₹4158/night",
    "image": "assets/images/hotels/dawki-hotel-114.jpg",
    "description": "A comfortable stay at Dawki."
  },
  {
    "id": "dawki-hotel-115",
    "name": "Dawki Resort",
    "type": "hotels",
    "city": "Dawki",
    "state": "Meghalaya",
    "rating": 4.8,
    "price": "₹7206/night",
    "image": "assets/images/hotels/dawki-hotel-115.jpg",
    "description": "A comfortable stay at Dawki."
  },
  {
    "id": "cherrapunji-hotel-116",
    "name": "Cherrapunji Grand",
    "type": "hotels",
    "city": "Cherrapunji",
    "state": "Meghalaya",
    "rating": 4,
    "price": "₹7126/night",
    "image": "assets/images/hotels/cherrapunji-hotel-116.jpg",
    "description": "A comfortable stay at Cherrapunji."
  },
  {
    "id": "champhai-hotel-117",
    "name": "Champhai Budget Hotel",
    "type": "hotels",
    "city": "Champhai",
    "state": "Mizoram",
    "rating": 3.7,
    "price": "₹7499/night",
    "image": "assets/images/hotels/champhai-hotel-117.jpg",
    "description": "A comfortable stay at Champhai."
  },
  {
    "id": "aizawl-hotel-118",
    "name": "Aizawl Resort",
    "type": "hotels",
    "city": "Aizawl",
    "state": "Mizoram",
    "rating": 4.8,
    "price": "₹5611/night",
    "image": "assets/images/hotels/aizawl-hotel-118.jpg",
    "description": "A comfortable stay at Aizawl."
  },
  {
    "id": "champhai-hotel-119",
    "name": "Champhai Luxury Hotel",
    "type": "hotels",
    "city": "Champhai",
    "state": "Mizoram",
    "rating": 3.6,
    "price": "₹1164/night",
    "image": "assets/images/hotels/champhai-hotel-119.jpg",
    "description": "A comfortable stay at Champhai."
  },
  {
    "id": "champhai-hotel-120",
    "name": "Champhai Resort",
    "type": "hotels",
    "city": "Champhai",
    "state": "Mizoram",
    "rating": 4.2,
    "price": "₹5405/night",
    "image": "assets/images/hotels/champhai-hotel-120.jpg",
    "description": "A comfortable stay at Champhai."
  },
  {
    "id": "aizawl-hotel-121",
    "name": "Aizawl Heritage Hotel",
    "type": "hotels",
    "city": "Aizawl",
    "state": "Mizoram",
    "rating": 4.4,
    "price": "₹1485/night",
    "image": "assets/images/hotels/aizawl-hotel-121.jpg",
    "description": "A comfortable stay at Aizawl."
  },
  {
    "id": "champhai-hotel-122",
    "name": "Champhai Grand",
    "type": "hotels",
    "city": "Champhai",
    "state": "Mizoram",
    "rating": 4.1,
    "price": "₹1733/night",
    "image": "assets/images/hotels/champhai-hotel-122.jpg",
    "description": "A comfortable stay at Champhai."
  },
  {
    "id": "kohima-hotel-123",
    "name": "Kohima Resort",
    "type": "hotels",
    "city": "Kohima",
    "state": "Nagaland",
    "rating": 4.7,
    "price": "₹6231/night",
    "image": "assets/images/hotels/kohima-hotel-123.jpg",
    "description": "A comfortable stay at Kohima."
  },
  {
    "id": "dimapur-hotel-124",
    "name": "Dimapur Budget Hotel",
    "type": "hotels",
    "city": "Dimapur",
    "state": "Nagaland",
    "rating": 4.4,
    "price": "₹1752/night",
    "image": "assets/images/hotels/dimapur-hotel-124.jpg",
    "description": "A comfortable stay at Dimapur."
  },
  {
    "id": "dimapur-hotel-125",
    "name": "Dimapur Luxury Hotel",
    "type": "hotels",
    "city": "Dimapur",
    "state": "Nagaland",
    "rating": 4.3,
    "price": "₹3694/night",
    "image": "assets/images/hotels/dimapur-hotel-125.jpg",
    "description": "A comfortable stay at Dimapur."
  },
  {
    "id": "kohima-hotel-126",
    "name": "Kohima Heritage Hotel",
    "type": "hotels",
    "city": "Kohima",
    "state": "Nagaland",
    "rating": 4.3,
    "price": "₹3147/night",
    "image": "assets/images/hotels/kohima-hotel-126.jpg",
    "description": "A comfortable stay at Kohima."
  },
  {
    "id": "dimapur-hotel-127",
    "name": "Dimapur Luxury Hotel",
    "type": "hotels",
    "city": "Dimapur",
    "state": "Nagaland",
    "rating": 4,
    "price": "₹6853/night",
    "image": "assets/images/hotels/dimapur-hotel-127.jpg",
    "description": "A comfortable stay at Dimapur."
  },
  {
    "id": "dimapur-hotel-128",
    "name": "Dimapur Luxury Hotel",
    "type": "hotels",
    "city": "Dimapur",
    "state": "Nagaland",
    "rating": 4.4,
    "price": "₹5935/night",
    "image": "assets/images/hotels/dimapur-hotel-128.jpg",
    "description": "A comfortable stay at Dimapur."
  },
  {
    "id": "puri-hotel-129",
    "name": "Puri Luxury Hotel",
    "type": "hotels",
    "city": "Puri",
    "state": "Odisha",
    "rating": 4.2,
    "price": "₹7737/night",
    "image": "assets/images/hotels/puri-hotel-129.jpg",
    "description": "A comfortable stay at Puri."
  },
  {
    "id": "bhubaneswar-hotel-130",
    "name": "Bhubaneswar Resort",
    "type": "hotels",
    "city": "Bhubaneswar",
    "state": "Odisha",
    "rating": 4.2,
    "price": "₹5420/night",
    "image": "assets/images/hotels/bhubaneswar-hotel-130.jpg",
    "description": "A comfortable stay at Bhubaneswar."
  },
  {
    "id": "cuttack-hotel-131",
    "name": "Cuttack Budget Hotel",
    "type": "hotels",
    "city": "Cuttack",
    "state": "Odisha",
    "rating": 4.6,
    "price": "₹2019/night",
    "image": "assets/images/hotels/cuttack-hotel-131.jpg",
    "description": "A comfortable stay at Cuttack."
  },
  {
    "id": "konark-hotel-132",
    "name": "Konark Resort",
    "type": "hotels",
    "city": "Konark",
    "state": "Odisha",
    "rating": 3.7,
    "price": "₹5177/night",
    "image": "assets/images/hotels/konark-hotel-132.jpg",
    "description": "A comfortable stay at Konark."
  },
  {
    "id": "konark-hotel-133",
    "name": "Konark Resort",
    "type": "hotels",
    "city": "Konark",
    "state": "Odisha",
    "rating": 4.7,
    "price": "₹8108/night",
    "image": "assets/images/hotels/konark-hotel-133.jpg",
    "description": "A comfortable stay at Konark."
  },
  {
    "id": "puri-hotel-134",
    "name": "Puri Resort",
    "type": "hotels",
    "city": "Puri",
    "state": "Odisha",
    "rating": 3.6,
    "price": "₹6761/night",
    "image": "assets/images/hotels/puri-hotel-134.jpg",
    "description": "A comfortable stay at Puri."
  },
  {
    "id": "ludhiana-hotel-135",
    "name": "Ludhiana Heritage Hotel",
    "type": "hotels",
    "city": "Ludhiana",
    "state": "Punjab",
    "rating": 3.7,
    "price": "₹1777/night",
    "image": "assets/images/hotels/ludhiana-hotel-135.jpg",
    "description": "A comfortable stay at Ludhiana."
  },
  {
    "id": "chandigarh-hotel-136",
    "name": "Chandigarh Grand",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Punjab",
    "rating": 3.7,
    "price": "₹6233/night",
    "image": "assets/images/hotels/chandigarh-hotel-136.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-137",
    "name": "Chandigarh Budget Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Punjab",
    "rating": 4,
    "price": "₹5111/night",
    "image": "assets/images/hotels/chandigarh-hotel-137.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "jalandhar-hotel-138",
    "name": "Jalandhar Heritage Hotel",
    "type": "hotels",
    "city": "Jalandhar",
    "state": "Punjab",
    "rating": 4.1,
    "price": "₹2014/night",
    "image": "assets/images/hotels/jalandhar-hotel-138.jpg",
    "description": "A comfortable stay at Jalandhar."
  },
  {
    "id": "jalandhar-hotel-139",
    "name": "Jalandhar Heritage Hotel",
    "type": "hotels",
    "city": "Jalandhar",
    "state": "Punjab",
    "rating": 4.8,
    "price": "₹1348/night",
    "image": "assets/images/hotels/jalandhar-hotel-139.jpg",
    "description": "A comfortable stay at Jalandhar."
  },
  {
    "id": "chandigarh-hotel-140",
    "name": "Chandigarh Luxury Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Punjab",
    "rating": 4.3,
    "price": "₹8975/night",
    "image": "assets/images/hotels/chandigarh-hotel-140.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "mount-abu-hotel-141",
    "name": "Mount Abu Luxury Hotel",
    "type": "hotels",
    "city": "Mount Abu",
    "state": "Rajasthan",
    "rating": 4.4,
    "price": "₹8048/night",
    "image": "assets/images/hotels/mount-abu-hotel-141.jpg",
    "description": "A comfortable stay at Mount Abu."
  },
  {
    "id": "pushkar-hotel-142",
    "name": "Pushkar Luxury Hotel",
    "type": "hotels",
    "city": "Pushkar",
    "state": "Rajasthan",
    "rating": 5,
    "price": "₹4158/night",
    "image": "assets/images/hotels/pushkar-hotel-142.jpg",
    "description": "A comfortable stay at Pushkar."
  },
  {
    "id": "mount-abu-hotel-143",
    "name": "Mount Abu Resort",
    "type": "hotels",
    "city": "Mount Abu",
    "state": "Rajasthan",
    "rating": 4.3,
    "price": "₹4425/night",
    "image": "assets/images/hotels/mount-abu-hotel-143.jpg",
    "description": "A comfortable stay at Mount Abu."
  },
  {
    "id": "pushkar-hotel-144",
    "name": "Pushkar Budget Hotel",
    "type": "hotels",
    "city": "Pushkar",
    "state": "Rajasthan",
    "rating": 4,
    "price": "₹7648/night",
    "image": "assets/images/hotels/pushkar-hotel-144.jpg",
    "description": "A comfortable stay at Pushkar."
  },
  {
    "id": "udaipur-hotel-145",
    "name": "Udaipur Budget Hotel",
    "type": "hotels",
    "city": "Udaipur",
    "state": "Rajasthan",
    "rating": 4.9,
    "price": "₹1751/night",
    "image": "assets/images/hotels/udaipur-hotel-145.jpg",
    "description": "A comfortable stay at Udaipur."
  },
  {
    "id": "jaipur-hotel-146",
    "name": "Jaipur Heritage Hotel",
    "type": "hotels",
    "city": "Jaipur",
    "state": "Rajasthan",
    "rating": 3.8,
    "price": "₹2507/night",
    "image": "assets/images/hotels/jaipur-hotel-146.jpg",
    "description": "A comfortable stay at Jaipur."
  },
  {
    "id": "pelling-hotel-147",
    "name": "Pelling Heritage Hotel",
    "type": "hotels",
    "city": "Pelling",
    "state": "Sikkim",
    "rating": 4.4,
    "price": "₹2248/night",
    "image": "assets/images/hotels/pelling-hotel-147.jpg",
    "description": "A comfortable stay at Pelling."
  },
  {
    "id": "lachen-hotel-148",
    "name": "Lachen Resort",
    "type": "hotels",
    "city": "Lachen",
    "state": "Sikkim",
    "rating": 3.6,
    "price": "₹5733/night",
    "image": "assets/images/hotels/lachen-hotel-148.jpg",
    "description": "A comfortable stay at Lachen."
  },
  {
    "id": "namchi-hotel-149",
    "name": "Namchi Heritage Hotel",
    "type": "hotels",
    "city": "Namchi",
    "state": "Sikkim",
    "rating": 4.5,
    "price": "₹8451/night",
    "image": "assets/images/hotels/namchi-hotel-149.jpg",
    "description": "A comfortable stay at Namchi."
  },
  {
    "id": "lachen-hotel-150",
    "name": "Lachen Grand",
    "type": "hotels",
    "city": "Lachen",
    "state": "Sikkim",
    "rating": 4.2,
    "price": "₹4056/night",
    "image": "assets/images/hotels/lachen-hotel-150.jpg",
    "description": "A comfortable stay at Lachen."
  },
  {
    "id": "lachen-hotel-151",
    "name": "Lachen Heritage Hotel",
    "type": "hotels",
    "city": "Lachen",
    "state": "Sikkim",
    "rating": 4.4,
    "price": "₹2566/night",
    "image": "assets/images/hotels/lachen-hotel-151.jpg",
    "description": "A comfortable stay at Lachen."
  },
  {
    "id": "lachen-hotel-152",
    "name": "Lachen Budget Hotel",
    "type": "hotels",
    "city": "Lachen",
    "state": "Sikkim",
    "rating": 4.7,
    "price": "₹7664/night",
    "image": "assets/images/hotels/lachen-hotel-152.jpg",
    "description": "A comfortable stay at Lachen."
  },
  {
    "id": "coimbatore-hotel-153",
    "name": "Coimbatore Luxury Hotel",
    "type": "hotels",
    "city": "Coimbatore",
    "state": "Tamil Nadu",
    "rating": 4.7,
    "price": "₹7581/night",
    "image": "assets/images/hotels/coimbatore-hotel-153.jpg",
    "description": "A comfortable stay at Coimbatore."
  },
  {
    "id": "coimbatore-hotel-154",
    "name": "Coimbatore Budget Hotel",
    "type": "hotels",
    "city": "Coimbatore",
    "state": "Tamil Nadu",
    "rating": 4.1,
    "price": "₹8493/night",
    "image": "assets/images/hotels/coimbatore-hotel-154.jpg",
    "description": "A comfortable stay at Coimbatore."
  },
  {
    "id": "mahabalipuram-hotel-155",
    "name": "Mahabalipuram Heritage Hotel",
    "type": "hotels",
    "city": "Mahabalipuram",
    "state": "Tamil Nadu",
    "rating": 3.7,
    "price": "₹4871/night",
    "image": "assets/images/hotels/mahabalipuram-hotel-155.jpg",
    "description": "A comfortable stay at Mahabalipuram."
  },
  {
    "id": "kanyakumari-hotel-156",
    "name": "Kanyakumari Resort",
    "type": "hotels",
    "city": "Kanyakumari",
    "state": "Tamil Nadu",
    "rating": 3.6,
    "price": "₹8302/night",
    "image": "assets/images/hotels/kanyakumari-hotel-156.jpg",
    "description": "A comfortable stay at Kanyakumari."
  },
  {
    "id": "madurai-hotel-157",
    "name": "Madurai Budget Hotel",
    "type": "hotels",
    "city": "Madurai",
    "state": "Tamil Nadu",
    "rating": 4.8,
    "price": "₹6030/night",
    "image": "assets/images/hotels/madurai-hotel-157.jpg",
    "description": "A comfortable stay at Madurai."
  },
  {
    "id": "coimbatore-hotel-158",
    "name": "Coimbatore Budget Hotel",
    "type": "hotels",
    "city": "Coimbatore",
    "state": "Tamil Nadu",
    "rating": 4.2,
    "price": "₹8359/night",
    "image": "assets/images/hotels/coimbatore-hotel-158.jpg",
    "description": "A comfortable stay at Coimbatore."
  },
  {
    "id": "hyderabad-hotel-159",
    "name": "Hyderabad Luxury Hotel",
    "type": "hotels",
    "city": "Hyderabad",
    "state": "Telangana",
    "rating": 4.9,
    "price": "₹3036/night",
    "image": "assets/images/hotels/hyderabad-hotel-159.jpg",
    "description": "A comfortable stay at Hyderabad."
  },
  {
    "id": "nizamabad-hotel-160",
    "name": "Nizamabad Luxury Hotel",
    "type": "hotels",
    "city": "Nizamabad",
    "state": "Telangana",
    "rating": 4.1,
    "price": "₹1415/night",
    "image": "assets/images/hotels/nizamabad-hotel-160.jpg",
    "description": "A comfortable stay at Nizamabad."
  },
  {
    "id": "hyderabad-hotel-161",
    "name": "Hyderabad Budget Hotel",
    "type": "hotels",
    "city": "Hyderabad",
    "state": "Telangana",
    "rating": 4.3,
    "price": "₹1325/night",
    "image": "assets/images/hotels/hyderabad-hotel-161.jpg",
    "description": "A comfortable stay at Hyderabad."
  },
  {
    "id": "hyderabad-hotel-162",
    "name": "Hyderabad Luxury Hotel",
    "type": "hotels",
    "city": "Hyderabad",
    "state": "Telangana",
    "rating": 3.7,
    "price": "₹6676/night",
    "image": "assets/images/hotels/hyderabad-hotel-162.jpg",
    "description": "A comfortable stay at Hyderabad."
  },
  {
    "id": "nizamabad-hotel-163",
    "name": "Nizamabad Grand",
    "type": "hotels",
    "city": "Nizamabad",
    "state": "Telangana",
    "rating": 4.9,
    "price": "₹4931/night",
    "image": "assets/images/hotels/nizamabad-hotel-163.jpg",
    "description": "A comfortable stay at Nizamabad."
  },
  {
    "id": "nizamabad-hotel-164",
    "name": "Nizamabad Budget Hotel",
    "type": "hotels",
    "city": "Nizamabad",
    "state": "Telangana",
    "rating": 4.1,
    "price": "₹6071/night",
    "image": "assets/images/hotels/nizamabad-hotel-164.jpg",
    "description": "A comfortable stay at Nizamabad."
  },
  {
    "id": "agartala-hotel-165",
    "name": "Agartala Heritage Hotel",
    "type": "hotels",
    "city": "Agartala",
    "state": "Tripura",
    "rating": 3.5,
    "price": "₹7614/night",
    "image": "assets/images/hotels/agartala-hotel-165.jpg",
    "description": "A comfortable stay at Agartala."
  },
  {
    "id": "agartala-hotel-166",
    "name": "Agartala Budget Hotel",
    "type": "hotels",
    "city": "Agartala",
    "state": "Tripura",
    "rating": 3.8,
    "price": "₹8677/night",
    "image": "assets/images/hotels/agartala-hotel-166.jpg",
    "description": "A comfortable stay at Agartala."
  },
  {
    "id": "agartala-hotel-167",
    "name": "Agartala Luxury Hotel",
    "type": "hotels",
    "city": "Agartala",
    "state": "Tripura",
    "rating": 4.1,
    "price": "₹7447/night",
    "image": "assets/images/hotels/agartala-hotel-167.jpg",
    "description": "A comfortable stay at Agartala."
  },
  {
    "id": "agartala-hotel-168",
    "name": "Agartala Luxury Hotel",
    "type": "hotels",
    "city": "Agartala",
    "state": "Tripura",
    "rating": 3.9,
    "price": "₹1508/night",
    "image": "assets/images/hotels/agartala-hotel-168.jpg",
    "description": "A comfortable stay at Agartala."
  },
  {
    "id": "agartala-hotel-169",
    "name": "Agartala Heritage Hotel",
    "type": "hotels",
    "city": "Agartala",
    "state": "Tripura",
    "rating": 4.7,
    "price": "₹7856/night",
    "image": "assets/images/hotels/agartala-hotel-169.jpg",
    "description": "A comfortable stay at Agartala."
  },
  {
    "id": "udaipur-hotel-170",
    "name": "Udaipur Resort",
    "type": "hotels",
    "city": "Udaipur",
    "state": "Tripura",
    "rating": 4.6,
    "price": "₹8697/night",
    "image": "assets/images/hotels/udaipur-hotel-170.jpg",
    "description": "A comfortable stay at Udaipur."
  },
  {
    "id": "varanasi-hotel-171",
    "name": "Varanasi Heritage Hotel",
    "type": "hotels",
    "city": "Varanasi",
    "state": "Uttar Pradesh",
    "rating": 3.8,
    "price": "₹3363/night",
    "image": "assets/images/hotels/varanasi-hotel-171.jpg",
    "description": "A comfortable stay at Varanasi."
  },
  {
    "id": "varanasi-hotel-172",
    "name": "Varanasi Heritage Hotel",
    "type": "hotels",
    "city": "Varanasi",
    "state": "Uttar Pradesh",
    "rating": 4.2,
    "price": "₹5238/night",
    "image": "assets/images/hotels/varanasi-hotel-172.jpg",
    "description": "A comfortable stay at Varanasi."
  },
  {
    "id": "agra-hotel-173",
    "name": "Agra Grand",
    "type": "hotels",
    "city": "Agra",
    "state": "Uttar Pradesh",
    "rating": 3.7,
    "price": "₹2830/night",
    "image": "assets/images/hotels/agra-hotel-173.jpg",
    "description": "A comfortable stay at Agra."
  },
  {
    "id": "lucknow-hotel-174",
    "name": "Lucknow Resort",
    "type": "hotels",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "rating": 3.9,
    "price": "₹1283/night",
    "image": "assets/images/hotels/lucknow-hotel-174.jpg",
    "description": "A comfortable stay at Lucknow."
  },
  {
    "id": "ayodhya-hotel-175",
    "name": "Ayodhya Grand",
    "type": "hotels",
    "city": "Ayodhya",
    "state": "Uttar Pradesh",
    "rating": 4.5,
    "price": "₹5253/night",
    "image": "assets/images/hotels/ayodhya-hotel-175.jpg",
    "description": "A comfortable stay at Ayodhya."
  },
  {
    "id": "mathura-hotel-176",
    "name": "Mathura Resort",
    "type": "hotels",
    "city": "Mathura",
    "state": "Uttar Pradesh",
    "rating": 4.4,
    "price": "₹4772/night",
    "image": "assets/images/hotels/mathura-hotel-176.jpg",
    "description": "A comfortable stay at Mathura."
  },
  {
    "id": "nainital-hotel-177",
    "name": "Nainital Heritage Hotel",
    "type": "hotels",
    "city": "Nainital",
    "state": "Uttarakhand",
    "rating": 4.1,
    "price": "₹6846/night",
    "image": "assets/images/hotels/nainital-hotel-177.jpg",
    "description": "A comfortable stay at Nainital."
  },
  {
    "id": "nainital-hotel-178",
    "name": "Nainital Luxury Hotel",
    "type": "hotels",
    "city": "Nainital",
    "state": "Uttarakhand",
    "rating": 3.7,
    "price": "₹4398/night",
    "image": "assets/images/hotels/nainital-hotel-178.jpg",
    "description": "A comfortable stay at Nainital."
  },
  {
    "id": "dehradun-hotel-179",
    "name": "Dehradun Resort",
    "type": "hotels",
    "city": "Dehradun",
    "state": "Uttarakhand",
    "rating": 4.5,
    "price": "₹2938/night",
    "image": "assets/images/hotels/dehradun-hotel-179.jpg",
    "description": "A comfortable stay at Dehradun."
  },
  {
    "id": "haridwar-hotel-180",
    "name": "Haridwar Grand",
    "type": "hotels",
    "city": "Haridwar",
    "state": "Uttarakhand",
    "rating": 3.9,
    "price": "₹6888/night",
    "image": "assets/images/hotels/haridwar-hotel-180.jpg",
    "description": "A comfortable stay at Haridwar."
  },
  {
    "id": "dehradun-hotel-181",
    "name": "Dehradun Heritage Hotel",
    "type": "hotels",
    "city": "Dehradun",
    "state": "Uttarakhand",
    "rating": 3.7,
    "price": "₹7743/night",
    "image": "assets/images/hotels/dehradun-hotel-181.jpg",
    "description": "A comfortable stay at Dehradun."
  },
  {
    "id": "mussoorie-hotel-182",
    "name": "Mussoorie Resort",
    "type": "hotels",
    "city": "Mussoorie",
    "state": "Uttarakhand",
    "rating": 4.5,
    "price": "₹2314/night",
    "image": "assets/images/hotels/mussoorie-hotel-182.jpg",
    "description": "A comfortable stay at Mussoorie."
  },
  {
    "id": "siliguri-hotel-183",
    "name": "Siliguri Resort",
    "type": "hotels",
    "city": "Siliguri",
    "state": "West Bengal",
    "rating": 4,
    "price": "₹2734/night",
    "image": "assets/images/hotels/siliguri-hotel-183.jpg",
    "description": "A comfortable stay at Siliguri."
  },
  {
    "id": "siliguri-hotel-184",
    "name": "Siliguri Budget Hotel",
    "type": "hotels",
    "city": "Siliguri",
    "state": "West Bengal",
    "rating": 4.1,
    "price": "₹6721/night",
    "image": "assets/images/hotels/siliguri-hotel-184.jpg",
    "description": "A comfortable stay at Siliguri."
  },
  {
    "id": "digha-hotel-185",
    "name": "Digha Budget Hotel",
    "type": "hotels",
    "city": "Digha",
    "state": "West Bengal",
    "rating": 3.9,
    "price": "₹7671/night",
    "image": "assets/images/hotels/digha-hotel-185.jpg",
    "description": "A comfortable stay at Digha."
  },
  {
    "id": "kolkata-hotel-186",
    "name": "Kolkata Grand",
    "type": "hotels",
    "city": "Kolkata",
    "state": "West Bengal",
    "rating": 4,
    "price": "₹8253/night",
    "image": "assets/images/hotels/kolkata-hotel-186.jpg",
    "description": "A comfortable stay at Kolkata."
  },
  {
    "id": "darjeeling-hotel-187",
    "name": "Darjeeling Grand",
    "type": "hotels",
    "city": "Darjeeling",
    "state": "West Bengal",
    "rating": 3.6,
    "price": "₹3221/night",
    "image": "assets/images/hotels/darjeeling-hotel-187.jpg",
    "description": "A comfortable stay at Darjeeling."
  },
  {
    "id": "darjeeling-hotel-188",
    "name": "Darjeeling Grand",
    "type": "hotels",
    "city": "Darjeeling",
    "state": "West Bengal",
    "rating": 4.1,
    "price": "₹5048/night",
    "image": "assets/images/hotels/darjeeling-hotel-188.jpg",
    "description": "A comfortable stay at Darjeeling."
  },
  {
    "id": "port-blair-hotel-189",
    "name": "Port Blair Grand",
    "type": "hotels",
    "city": "Port Blair",
    "state": "Andaman and Nicobar Islands",
    "rating": 4.7,
    "price": "₹6941/night",
    "image": "assets/images/hotels/port-blair-hotel-189.jpg",
    "description": "A comfortable stay at Port Blair."
  },
  {
    "id": "neil-island-hotel-190",
    "name": "Neil Island Budget Hotel",
    "type": "hotels",
    "city": "Neil Island",
    "state": "Andaman and Nicobar Islands",
    "rating": 3.6,
    "price": "₹4827/night",
    "image": "assets/images/hotels/neil-island-hotel-190.jpg",
    "description": "A comfortable stay at Neil Island."
  },
  {
    "id": "neil-island-hotel-191",
    "name": "Neil Island Resort",
    "type": "hotels",
    "city": "Neil Island",
    "state": "Andaman and Nicobar Islands",
    "rating": 4.9,
    "price": "₹4263/night",
    "image": "assets/images/hotels/neil-island-hotel-191.jpg",
    "description": "A comfortable stay at Neil Island."
  },
  {
    "id": "port-blair-hotel-192",
    "name": "Port Blair Heritage Hotel",
    "type": "hotels",
    "city": "Port Blair",
    "state": "Andaman and Nicobar Islands",
    "rating": 4.6,
    "price": "₹4848/night",
    "image": "assets/images/hotels/port-blair-hotel-192.jpg",
    "description": "A comfortable stay at Port Blair."
  },
  {
    "id": "port-blair-hotel-193",
    "name": "Port Blair Resort",
    "type": "hotels",
    "city": "Port Blair",
    "state": "Andaman and Nicobar Islands",
    "rating": 4.7,
    "price": "₹3598/night",
    "image": "assets/images/hotels/port-blair-hotel-193.jpg",
    "description": "A comfortable stay at Port Blair."
  },
  {
    "id": "neil-island-hotel-194",
    "name": "Neil Island Grand",
    "type": "hotels",
    "city": "Neil Island",
    "state": "Andaman and Nicobar Islands",
    "rating": 4.2,
    "price": "₹4698/night",
    "image": "assets/images/hotels/neil-island-hotel-194.jpg",
    "description": "A comfortable stay at Neil Island."
  },
  {
    "id": "chandigarh-hotel-195",
    "name": "Chandigarh Heritage Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 5,
    "price": "₹5871/night",
    "image": "assets/images/hotels/chandigarh-hotel-195.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-196",
    "name": "Chandigarh Luxury Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 3.6,
    "price": "₹3226/night",
    "image": "assets/images/hotels/chandigarh-hotel-196.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-197",
    "name": "Chandigarh Budget Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 4.4,
    "price": "₹6254/night",
    "image": "assets/images/hotels/chandigarh-hotel-197.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-198",
    "name": "Chandigarh Resort",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 3.7,
    "price": "₹4467/night",
    "image": "assets/images/hotels/chandigarh-hotel-198.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-199",
    "name": "Chandigarh Heritage Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 3.6,
    "price": "₹4864/night",
    "image": "assets/images/hotels/chandigarh-hotel-199.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "chandigarh-hotel-200",
    "name": "Chandigarh Heritage Hotel",
    "type": "hotels",
    "city": "Chandigarh",
    "state": "Chandigarh",
    "rating": 4.8,
    "price": "₹7844/night",
    "image": "assets/images/hotels/chandigarh-hotel-200.jpg",
    "description": "A comfortable stay at Chandigarh."
  },
  {
    "id": "silvassa-hotel-201",
    "name": "Silvassa Luxury Hotel",
    "type": "hotels",
    "city": "Silvassa",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 4,
    "price": "₹7800/night",
    "image": "assets/images/hotels/silvassa-hotel-201.jpg",
    "description": "A comfortable stay at Silvassa."
  },
  {
    "id": "daman-hotel-202",
    "name": "Daman Luxury Hotel",
    "type": "hotels",
    "city": "Daman",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 3.8,
    "price": "₹1931/night",
    "image": "assets/images/hotels/daman-hotel-202.jpg",
    "description": "A comfortable stay at Daman."
  },
  {
    "id": "diu-hotel-203",
    "name": "Diu Grand",
    "type": "hotels",
    "city": "Diu",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 4.6,
    "price": "₹4973/night",
    "image": "assets/images/hotels/diu-hotel-203.jpg",
    "description": "A comfortable stay at Diu."
  },
  {
    "id": "daman-hotel-204",
    "name": "Daman Heritage Hotel",
    "type": "hotels",
    "city": "Daman",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 4.6,
    "price": "₹1144/night",
    "image": "assets/images/hotels/daman-hotel-204.jpg",
    "description": "A comfortable stay at Daman."
  },
  {
    "id": "silvassa-hotel-205",
    "name": "Silvassa Grand",
    "type": "hotels",
    "city": "Silvassa",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 3.6,
    "price": "₹5456/night",
    "image": "assets/images/hotels/silvassa-hotel-205.jpg",
    "description": "A comfortable stay at Silvassa."
  },
  {
    "id": "silvassa-hotel-206",
    "name": "Silvassa Grand",
    "type": "hotels",
    "city": "Silvassa",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "rating": 4.3,
    "price": "₹5911/night",
    "image": "assets/images/hotels/silvassa-hotel-206.jpg",
    "description": "A comfortable stay at Silvassa."
  },
  {
    "id": "south-delhi-hotel-207",
    "name": "South Delhi Luxury Hotel",
    "type": "hotels",
    "city": "South Delhi",
    "state": "Delhi",
    "rating": 4.5,
    "price": "₹4651/night",
    "image": "assets/images/hotels/south-delhi-hotel-207.jpg",
    "description": "A comfortable stay at South Delhi."
  },
  {
    "id": "new-delhi-hotel-208",
    "name": "New Delhi Budget Hotel",
    "type": "hotels",
    "city": "New Delhi",
    "state": "Delhi",
    "rating": 3.8,
    "price": "₹5691/night",
    "image": "assets/images/hotels/new-delhi-hotel-208.jpg",
    "description": "A comfortable stay at New Delhi."
  },
  {
    "id": "old-delhi-hotel-209",
    "name": "Old Delhi Budget Hotel",
    "type": "hotels",
    "city": "Old Delhi",
    "state": "Delhi",
    "rating": 3.6,
    "price": "₹3010/night",
    "image": "assets/images/hotels/old-delhi-hotel-209.jpg",
    "description": "A comfortable stay at Old Delhi."
  },
  {
    "id": "south-delhi-hotel-210",
    "name": "South Delhi Heritage Hotel",
    "type": "hotels",
    "city": "South Delhi",
    "state": "Delhi",
    "rating": 4.7,
    "price": "₹6708/night",
    "image": "assets/images/hotels/south-delhi-hotel-210.jpg",
    "description": "A comfortable stay at South Delhi."
  },
  {
    "id": "new-delhi-hotel-211",
    "name": "New Delhi Luxury Hotel",
    "type": "hotels",
    "city": "New Delhi",
    "state": "Delhi",
    "rating": 4.2,
    "price": "₹6737/night",
    "image": "assets/images/hotels/new-delhi-hotel-211.jpg",
    "description": "A comfortable stay at New Delhi."
  },
  {
    "id": "old-delhi-hotel-212",
    "name": "Old Delhi Budget Hotel",
    "type": "hotels",
    "city": "Old Delhi",
    "state": "Delhi",
    "rating": 4.4,
    "price": "₹6070/night",
    "image": "assets/images/hotels/old-delhi-hotel-212.jpg",
    "description": "A comfortable stay at Old Delhi."
  },
  {
    "id": "pahalgam-hotel-213",
    "name": "Pahalgam Luxury Hotel",
    "type": "hotels",
    "city": "Pahalgam",
    "state": "Jammu and Kashmir",
    "rating": 4.2,
    "price": "₹3510/night",
    "image": "assets/images/hotels/pahalgam-hotel-213.jpg",
    "description": "A comfortable stay at Pahalgam."
  },
  {
    "id": "pahalgam-hotel-214",
    "name": "Pahalgam Luxury Hotel",
    "type": "hotels",
    "city": "Pahalgam",
    "state": "Jammu and Kashmir",
    "rating": 3.7,
    "price": "₹7496/night",
    "image": "assets/images/hotels/pahalgam-hotel-214.jpg",
    "description": "A comfortable stay at Pahalgam."
  },
  {
    "id": "srinagar-hotel-215",
    "name": "Srinagar Resort",
    "type": "hotels",
    "city": "Srinagar",
    "state": "Jammu and Kashmir",
    "rating": 4.6,
    "price": "₹5573/night",
    "image": "assets/images/hotels/srinagar-hotel-215.jpg",
    "description": "A comfortable stay at Srinagar."
  },
  {
    "id": "srinagar-hotel-216",
    "name": "Srinagar Luxury Hotel",
    "type": "hotels",
    "city": "Srinagar",
    "state": "Jammu and Kashmir",
    "rating": 4.6,
    "price": "₹5434/night",
    "image": "assets/images/hotels/srinagar-hotel-216.jpg",
    "description": "A comfortable stay at Srinagar."
  },
  {
    "id": "pahalgam-hotel-217",
    "name": "Pahalgam Luxury Hotel",
    "type": "hotels",
    "city": "Pahalgam",
    "state": "Jammu and Kashmir",
    "rating": 4.6,
    "price": "₹1735/night",
    "image": "assets/images/hotels/pahalgam-hotel-217.jpg",
    "description": "A comfortable stay at Pahalgam."
  },
  {
    "id": "sonamarg-hotel-218",
    "name": "Sonamarg Resort",
    "type": "hotels",
    "city": "Sonamarg",
    "state": "Jammu and Kashmir",
    "rating": 3.8,
    "price": "₹2768/night",
    "image": "assets/images/hotels/sonamarg-hotel-218.jpg",
    "description": "A comfortable stay at Sonamarg."
  },
  {
    "id": "pangong-hotel-219",
    "name": "Pangong Grand",
    "type": "hotels",
    "city": "Pangong",
    "state": "Ladakh",
    "rating": 4.8,
    "price": "₹4676/night",
    "image": "assets/images/hotels/pangong-hotel-219.jpg",
    "description": "A comfortable stay at Pangong."
  },
  {
    "id": "pangong-hotel-220",
    "name": "Pangong Resort",
    "type": "hotels",
    "city": "Pangong",
    "state": "Ladakh",
    "rating": 4.5,
    "price": "₹1663/night",
    "image": "assets/images/hotels/pangong-hotel-220.jpg",
    "description": "A comfortable stay at Pangong."
  },
  {
    "id": "leh-hotel-221",
    "name": "Leh Grand",
    "type": "hotels",
    "city": "Leh",
    "state": "Ladakh",
    "rating": 4.4,
    "price": "₹3617/night",
    "image": "assets/images/hotels/leh-hotel-221.jpg",
    "description": "A comfortable stay at Leh."
  },
  {
    "id": "kargil-hotel-222",
    "name": "Kargil Budget Hotel",
    "type": "hotels",
    "city": "Kargil",
    "state": "Ladakh",
    "rating": 3.9,
    "price": "₹7096/night",
    "image": "assets/images/hotels/kargil-hotel-222.jpg",
    "description": "A comfortable stay at Kargil."
  },
  {
    "id": "kargil-hotel-223",
    "name": "Kargil Luxury Hotel",
    "type": "hotels",
    "city": "Kargil",
    "state": "Ladakh",
    "rating": 3.6,
    "price": "₹8961/night",
    "image": "assets/images/hotels/kargil-hotel-223.jpg",
    "description": "A comfortable stay at Kargil."
  },
  {
    "id": "pangong-hotel-224",
    "name": "Pangong Heritage Hotel",
    "type": "hotels",
    "city": "Pangong",
    "state": "Ladakh",
    "rating": 4.2,
    "price": "₹8150/night",
    "image": "assets/images/hotels/pangong-hotel-224.jpg",
    "description": "A comfortable stay at Pangong."
  },
  {
    "id": "minicoy-hotel-225",
    "name": "Minicoy Luxury Hotel",
    "type": "hotels",
    "city": "Minicoy",
    "state": "Lakshadweep",
    "rating": 4.8,
    "price": "₹4905/night",
    "image": "assets/images/hotels/minicoy-hotel-225.jpg",
    "description": "A comfortable stay at Minicoy."
  },
  {
    "id": "kavaratti-hotel-226",
    "name": "Kavaratti Budget Hotel",
    "type": "hotels",
    "city": "Kavaratti",
    "state": "Lakshadweep",
    "rating": 3.8,
    "price": "₹4309/night",
    "image": "assets/images/hotels/kavaratti-hotel-226.jpg",
    "description": "A comfortable stay at Kavaratti."
  },
  {
    "id": "minicoy-hotel-227",
    "name": "Minicoy Resort",
    "type": "hotels",
    "city": "Minicoy",
    "state": "Lakshadweep",
    "rating": 4.2,
    "price": "₹2261/night",
    "image": "assets/images/hotels/minicoy-hotel-227.jpg",
    "description": "A comfortable stay at Minicoy."
  },
  {
    "id": "minicoy-hotel-228",
    "name": "Minicoy Luxury Hotel",
    "type": "hotels",
    "city": "Minicoy",
    "state": "Lakshadweep",
    "rating": 4.8,
    "price": "₹8561/night",
    "image": "assets/images/hotels/minicoy-hotel-228.jpg",
    "description": "A comfortable stay at Minicoy."
  },
  {
    "id": "kavaratti-hotel-229",
    "name": "Kavaratti Grand",
    "type": "hotels",
    "city": "Kavaratti",
    "state": "Lakshadweep",
    "rating": 5,
    "price": "₹1962/night",
    "image": "assets/images/hotels/kavaratti-hotel-229.jpg",
    "description": "A comfortable stay at Kavaratti."
  },
  {
    "id": "agatti-hotel-230",
    "name": "Agatti Heritage Hotel",
    "type": "hotels",
    "city": "Agatti",
    "state": "Lakshadweep",
    "rating": 4.5,
    "price": "₹7457/night",
    "image": "assets/images/hotels/agatti-hotel-230.jpg",
    "description": "A comfortable stay at Agatti."
  },
  {
    "id": "karaikal-hotel-231",
    "name": "Karaikal Budget Hotel",
    "type": "hotels",
    "city": "Karaikal",
    "state": "Puducherry",
    "rating": 4.8,
    "price": "₹4558/night",
    "image": "assets/images/hotels/karaikal-hotel-231.jpg",
    "description": "A comfortable stay at Karaikal."
  },
  {
    "id": "pondicherry-hotel-232",
    "name": "Pondicherry Grand",
    "type": "hotels",
    "city": "Pondicherry",
    "state": "Puducherry",
    "rating": 4.3,
    "price": "₹8759/night",
    "image": "assets/images/hotels/pondicherry-hotel-232.jpg",
    "description": "A comfortable stay at Pondicherry."
  },
  {
    "id": "auroville-hotel-233",
    "name": "Auroville Resort",
    "type": "hotels",
    "city": "Auroville",
    "state": "Puducherry",
    "rating": 3.9,
    "price": "₹6796/night",
    "image": "assets/images/hotels/auroville-hotel-233.jpg",
    "description": "A comfortable stay at Auroville."
  },
  {
    "id": "auroville-hotel-234",
    "name": "Auroville Budget Hotel",
    "type": "hotels",
    "city": "Auroville",
    "state": "Puducherry",
    "rating": 4.9,
    "price": "₹1411/night",
    "image": "assets/images/hotels/auroville-hotel-234.jpg",
    "description": "A comfortable stay at Auroville."
  },
  {
    "id": "auroville-hotel-235",
    "name": "Auroville Heritage Hotel",
    "type": "hotels",
    "city": "Auroville",
    "state": "Puducherry",
    "rating": 5,
    "price": "₹2382/night",
    "image": "assets/images/hotels/auroville-hotel-235.jpg",
    "description": "A comfortable stay at Auroville."
  },
  {
    "id": "auroville-hotel-236",
    "name": "Auroville Grand",
    "type": "hotels",
    "city": "Auroville",
    "state": "Puducherry",
    "rating": 3.6,
    "price": "₹8512/night",
    "image": "assets/images/hotels/auroville-hotel-236.jpg",
    "description": "A comfortable stay at Auroville."
  }
];